
services:
  Vita_WebAPI:
    image: vitawebapi:prod
    build:
      context: .
      dockerfile: Dockerfile.Prod
    ports:
      - "8081:5001"
    depends_on:
      - Vita_WebAPI_Database


  Vita_WebAPI_Database:
    image: mongo:latest
    container_name: Vita_WebAPI_Database
    ports:
      - "27017:27017"  # Exposes MongoDB on port 27017
    volumes:
      - Vita_db_data:/data/db  # Persistent storage for MongoDB data

volumes:
  Vita_db_data:
