version: '3.8'

services:
  webapi:
    build:
      context: .  # Use the current directory as the build context
      dockerfile: Dockerfile  # Ensure Dockerfile is in the context directory
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=db;Database=TestDb;User Id=sa;Password=Bbktbb11;TrustServerCertificate=True;"

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Bbktbb11"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

volumes:
  sql_data:

