name: .NET Build :wall

on:
  workflow_dispatch:
  push:
    branches:
      - main
  
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'  # Angiv din .NET-version her

    - name: Restore dependencies
      run: dotnet restore ./Vita/Vita_WebApi.sln

    - name: Build
      run: dotnet build ./Vita/Vita_WebApi.sln --configuration Release --no-restore

    - name: Publish
    - run: dotnet publish ./Vita/Vita_WebApi.sln --configuration Release --no-restore
