name: .NET CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    services:
      mongo:
        image: mongo:6.0
        ports:
          - 27017:27017
        options: --health-cmd "nc -z localhost 27017" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        env:
          MONGODB_CONNECTION_STRING: mongodb://localhost:27017
        run: dotnet test --no-build --verbosity normal

      # Optional: Save and upload test results (for better visibility)
      - name: Upload Test Results
        if: ${{ runner.os == 'windows-latest' }}
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: |
            **/TestResults/*.xml
