name: .NET Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'  # Angiv din .NET-version her
    
    - name: Install ctrf
      run: npm install github-actions-ctrf@0.0.29
        
    - name: mongo-action
      uses: DigiPie/mongo-action@v2.0.1
      with:
        port: 27017
          

    - name: Restore dependencies
      run: dotnet restore ./Vita_WebAPI/Vita_WebAPI.generated.sln

    - name: Restore test dependencies
      run: dotnet restore ./Vita_WebAPI/Vita_Test/Vita_Test.csproj 

    - name: Build
      run: dotnet build ./Vita_WebAPI/Vita_WebAPI.generated.sln --configuration Release --no-restore
    
    - name: Manifesto
      run: dotnet new tool-manifest
      
    - name: DotnetCTRFreporter
      run: dotnet tool install DotnetCtrfJsonReporter --local
      
    - name: Test
      run: dotnet test ./Vita_WebAPI/Vita_Test/Vita_Test.csproj --logger "trx;logfilename=testResults.trx"
    
    - name: convert
      run: dotnet tool run DotnetCtrfJsonReporter -p "/home/runner/work/Vita/Vita/Vita_WebAPI/Vita_Test/TestResults/testResults.trx"

    - name: Hvad er hvor, TestResults?
      run: ls /home/runner/work/Vita/Vita/Vita_WebAPI/Vita_Test/TestResults/

    - name: Er der en CTRL
      run: find -name ctrf
    
    - name: Publish Test Summary Results
      run: npx github-actions-ctrf "/home/runner/work/Vita/Vita/Vita_WebAPI/Vita_Test/TestResults/ctrf/ctrf-report.json"
    
    
    - name: Publish
      run: dotnet publish ./Vita_WebAPI/Vita_WebAPI.generated.sln --configuration Release --no-restore
